platform :ios, '12.0'
use_frameworks!

target 'AnyAPI_Example' do
  pod 'AnyAPI', :path => '../'
  pod 'SwiftLint' 
  
  target 'AnyAPI_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
